version: 1
sequences:
- protein:
    id: H
    sequence: QEQLVESGGGLVQPEGSLTLTCTASGIDFSRYYYMCWVRQAPGKGLEWVACIYAGSGGGTYYANWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARGPGNSGGVSDFFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AYDMTQTPASVEVAVGGTVTIKCQASESISNYLSWYQQKPGQPPKLLIYRASTLASGVSSRFKGSGSGTQFTLTISGVECADAATYYCQQGYSNTNLDNAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
