version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGGLVQPEGSLTLTCTASGFSFSGSIYMSWVRQAPGKGLEWIGCIATASDNTYYASWAKGRFTSSRSTSLNTVTLQMTSLTAADTATYFCATSDIGSSRYTFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: ALVMTQTPASVSEPVGGTVTIKCQASQSIGSNLAWYQQKPGQPPKLLIYYASTLASGVPSRFKGSGSGTQFTLTISDVQCDDAATYYCAGGYSSSSDNAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
