version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCTASGFSFSSGYDMCWVRQAPGKGLEWIACIYAGSGGSTYYASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARSPNVDSGWRLCYFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AQVLTQTPSSVSAAVGGTVTINCQASQSVYNNNQCSWFQQKPGQPPKQLIYRASNLETGVSSRFKGSGSGTQFTLTISDVQCDDAATYYCQGRFSDSSADSFAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
