version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPEGSLTLTCTASGFSFSSGYDMCWVRQAPGKGLEWIGCIDTGSGNTDSASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARGPAYSDYDLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AIVMTQTPSSKSVPVGDTVTINCQASESVYSNNRLSWFQQKPGQPPKLLIYAASTLASGVPSRFKGSGSGTQFTLTIRDVVCDDAATYYCAGYKSSSTDGHAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
