version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCTASGFSFSSSYYMCWVRQAPGKGLEWIGCIYTGSGSTYYASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARDYDDFGDCFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AIVMTQTPSSKSVPVGDTVTINCQASESVYSNNRLAGYQQKPGQPPKLLIYLASTLASGVPSRFKGSGSGTEFALTVSGVQCDDAATYYCQGEFSCSSADCNAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
