version: 1
sequences:
- protein:
    id: H
    sequence: QEQLEESGGDLVKPEGSLTLTCTASGFSFSSNYYMCWVRQAPGKGLEWIGCIYAGAETYPHYASWARGRFTISKTSSTTLTLQMTSLTDADTATYFCARSGSSNSGGLHYLDLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: DVVMTQTPASVEAAVGGTVTIKCQASQSISSYLAWYQQKPGQPPKLLIYKASTLASGVPSRFKGSGSGTQFTLTISGVQCDDAATYYCLGGYDDDADRGAFGGGTGVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
