version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCTASGFSFSSSYYMCWVRQAPGKGLEWIACIYTGSSGSTYYASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCGRGYGNSGGIPDYFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AFEMTQTPASVSEPVGGTVTIKCQASESIGSRLAWYQQKPGQPPKLLIYSASTLASGVSSRFKGSGSGTQFTLTISDLECADAATYYCQSYYDSNSIGAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
