version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCKASGIDFSRYYYMCWVRQAPGKGLEWIACIYTGSGSTYYASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARGDGNSGGIPDYFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: ALVLTQTPSPVSAAVGGTVTIKCQSSPSVYDNYCSWYQQKPGQPPKLLIYRTSTLASGVPSRFKGSGSGTQFTLTISGVECDDAATYYCAGYKDYNNDDNAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
