version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCTASGFSFSSSYWISWVRQAPGKGLEWIACIYAGSSGSTYYASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARSYYFAVWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AIVMTQTPSSKSVPVGDTVTINCQASESVYNNNNLAWFQQKPGQPPKLLIYKASTLASGVPSRFKGSGSGTQFTLTISDVVCDDAATYYCAGYKTYNDDGDRFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
