version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCTASGFSFSSSYYMCWVRQAPGKGLEWIACIYGASSGSTYYASWAKGRFSSSKTSSTTVTLQMTSLTAADTATYFCVRNMNDGSSLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AIVMTQTPSSKSVPVGDTVTINCQASESVYRHNECAWYQQKPGQPPKLLIYTASTLASGVPSRFKGSGSGTQFTLTISGVQCDDAATYYCAGHRSSSTDGTAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
