version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCTASGFSFSSAYDMNWVRQAPGRGREWIQYIYAGDGSTYSAGWAKGRFTISKTSSTTVDLKMTSLTAADTATYFCARGEGSSGWAFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AYDMTQTPASVEVAVGGTVTIKCQASQSIFNYLSWYHQKPGQPPKLLISRASTLESGVPSRFKGSGSGTEFTLTISDLECADAATYYCQQAYTISNLDNTFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
