version: 1
sequences:
- protein:
    id: H
    sequence: QEQLEESGGDLVKPEGSLTLTCKASGFSFGSYYMCWVRQAPGKRPEWIACIYTGDGITYYASWAKGRFSISRTSSTTVTLQMTSLTAADTATYFCARAAGIGSDYFKLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: DIVMTQTPASVSEPVGGTVTINCQASQSINSWLTWYQQKPGQPPKLLIYKASTLASGVPSRFKGSGSGTEFTLTISDLECDDVATYYCQSAYYISSVPFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
