version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDLVKPGASLTLTCKASGIDFSRYYYMCWVRQAPGKGLEWIACIYTGSGSTYYASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARGDGNSGGIPDYFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AYDMTQTPASVEVAVGGTVTIKCQASQSISSYLSWYQQKPGQRPKLLIYKASTLASGVSSRFKGSGSGTEFTLTISDLECADAATYYCQQAYSISNVDNAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
