version: 1
sequences:
- protein:
    id: H
    sequence: QEQLEESGGDLVKPEGSLTLTCTASGFSFSSGYDMCWVRQAPGKGLEWIACIYTGSSGSTYYASWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCAREEPYADAGVLYTKNYFKLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: DVVMTQTPASVSEPVGGTVTIKCQASQSISSYLAWYQQKPGQPPKLLIYRASTLASGVSSRFKGSGSGTEFTLTISGVECADAATYYCQQGYSSSNVDNAFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
