version: 1
sequences:
- protein:
    id: H
    sequence: QEQLEESGGDLVKPGASLTLICTASGFSFSNSYWSCWVRQAPGKGLEWIACFYAGSSDSTYYSSWAKGRFTISKTSSTTVTLQLTSLTAADTATYFCARSPYGGYNGYGYPYNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: DIVMTQTPASVSEPVGGTVTIKCQASQSISSYLSWYQQKPGQPPKRLIYKASTLASGVPSRFKGSGSGTEYTLTISGVQCDDAATYYCQQGYSRSNVDNVFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
