version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGGLVQPEGSLTLTCTASGFSFSSSYYMCWVRQAPGKGLEWIGCITTGSSITYYASWAKGRFTVSRAPSTTVTLQMTSLTAADTATYFCARGPDYSHYDLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: DIVMTQTPASVSEPVGGTVTIKCQASQSISPYLAWYQQKPGQRPKLLIYGASNLASGVSSRFKGSGSGTEFTLTISDLECDDAATYYCQTYYYSSGSSDGHVFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
