version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGGLVQPEGSLTLTCTASGFSFSSSYYMCWVRQAPGKGLEWIGCITTGSSITYYASWAKGRFTVSRAPSTTVTLQMTSLTAADTATYFCARGPDYSHYDLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: AIVMTQTPSSKSVPVGDTVTINCQASESVYNNNRLAWFQQKPGQPPKLLVYYASTLASGVPSRFKGSGSGTQFTLTISDLECDDAATYYCAGDYSSNGYVFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
