version: 1
sequences:
- protein:
    id: H
    sequence: QSLEESGGDPVQPGASLSLTCKVSGIDFSRYYYMCWVRQAPGKGLEWIACFYGGGSGATYYANWAKGRFTISKTSSTTVTLQMTSLTAADTATYFCARGVDYNGGNAAFNLWGPGTLVTVSSGQPKAPSVFPLAPCCG
- protein:
    id: L
    sequence: DVVMTQTPASVEAAVGGTVTIKCQASESISSRLAWYQQKPGQPPKLLIYRASTLESGVPSRFKGSGSGTEFTLTISDLECADAATYYCQGYYGSSSTSRHGFGGGTEVVVKG
- protein:
    id: A
    sequence: EPPTACREKQYLINSQCCSLCQPGQKLVSDCTEFTETECLPCGESEFLDTWNRETHCHQHKYCDPNLGLRVQQKGTSETDTICTCEEGWHCTSEACESCVLHRSCSPGFGVKQIATGVSDTICEPCPVGFFSNVSSAFEKCHPWTSCETKDLVVQQAGTNKTDVVCGPQDRLR
